POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "secure12345"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjFhOGJhNzEwYzFiMTMyZDA4MzczNCIsImlhdCI6MTc1NjQ3NTgwOCwiZXhwIjoxNzU2NDc5NDA4fQ.-vJGX1FgkB0bPk4QWDIQ0r04Aw6I5zbBkpZCP0ipg14