### obtener todos los cars
GET http://localhost:3000/api/cars

### obtener un car
GET http://localhost:3000/api/cars/1

### crear un nuevo car
POST http://localhost:3000/api/cars
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "color": "Blue",
  "price": 45000000,
  "available": true
}

### modificar un car (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cars/1
Content-Type: application/json

{
  "id": 1,
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "color": "Blue",
  "price": 100000,
  "available": true
}

### modificar un car (PATCH - recurso parcial)
PATCH http://localhost:3000/api/cars/1
Content-Type: application/json

{
  "price": 150000,
  "available": false
}

### borrar un car
DELETE http://localhost:3000/api/cars/1
