POST http://localhost:3000/api/rentals
Content-Type: application/json

{
  "userId": "68b1a8ba710c1b132d083734",
  "carId": 1,
  "startDate": "2024-07-01",
  "endDate": "2024-07-10",
  "price": 500.00,
  "status": "reserved"
}
###
GET http://localhost:3000/api/rentals
###

